version: '3.8'

services:
  contactpage:
    build: .
    container_name: contactpage_frontend
    restart: always
    ports:
      - "1234:80"
    env_file:
      - .env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    networks:
      - root_default

  backend:
    build:
      context: ../backend
    container_name: contactpage_backend
    restart: always
    ports:
      - "3001:3001"
      - .env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    networks:
      - root_default

networks:
  root_default:
    external: true
