version: '3.8'

services:
  contactpage:
    build: .
    container_name: contactpage_frontend
    restart: always
    ports:
      - "1234:80"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    networks:
      - root_default

networks:
  root_default:
    external: true
